### ISSUE TITLE
Trying the on-prem solution, but google sheet doesn't work. 

### ISSUE THREAD

**Issue by bayeslearner** [uibakery/self-hosted#89]
I have a google sheet that is shared for everyone with the link.  
Can't get UI bakery  to connect, although UI-bakery says it's successful in authenticating.

**Comment by spherebread** [comment]
Hi @bayeslearner,

Sorry for the late reply, our default support channels are support@uibakery.io and in-app chat 🙈

Is it still actual? We recently updated [our documentation](https://docs.uibakery.io/on-premise/google-sheets-connection-setup) regarding Google Sheets connection, please ensure that your on-premise instance is configured correctly.

In case of any issues — feel free to ping us.
