### ISSUE TITLE
Self-hosted issue / lagging and checkbox not working

### ISSUE THREAD

**Issue by zeus-hg** [uibakery/self-hosted#91]
Hello,
Really love your work. After some testing I have two issues:
1. When I check the checkbox: "reset form after submitting" after click submit button at the form, filled fields stays with data inserted even that data goes perfectly to mysql by query. How to clear form from data?
2. After adding more then 4-5 fields to form structure it starts to lagging a lot (waiting 1-2min every time I want to change name of the field, some settings etc.). Google Chrome Console shows Uncaught RangeError: Maximum call stack size exceeded - maybe is connected.
Thank you for help in advance.

**Comment by spherebread** [comment]
Hey @zeus-hg,
Thanks for reaching out 🫶

1. What's you version of the UI Bakery? Just tested on v3.63.2 — form resets after successful "onSubmit" action 🤔
2. Something unusual happening, form shouldn't be laggy even with 10 or more fields. Do you using any Custom Code on top of your app? Could you please provide a screencast of described behavior as a follow-up to your email?

Looking forward to your reply!

**Comment by zeus-hg** [comment]
Hello,
My version of UI Bakery is v3.63.2 I implemented on fresh installed Ubuntu 22.04.3 LTS.
I recorded submit not reseting data and lagging form and send you by email.
Hope to hear from you soon.
